using System.Collections.Generic;
using UnityEngine;

namespace ProceduralTerrain
{
    // Connects camp, build site, and resource clusters with a low-cost path
    // network generated by a genuine Prim's-algorithm minimum spanning tree
    // (NativeBridge.GeneratePathNetwork -> PathNetwork.cpp's ComputePrimsMST)
    // — not the DFS maze carver in LevelEditor/ProceduralGeneration.cs, and
    // not Perlin noise. Rasterized edges lower tile movement weight, so the
    // "weights" half of A* has a visible, useful payoff: agents that know
    // about the path network route through it instead of cutting overland.
    public static class PrimsPathNetworkBuilder
    {
        private const int MaxResourceSamplesPerType = 2;
        private const float PathWeight = 0.4f;

        public static void BuildNetwork(PrimsTerrainGenerator generator, Vector2Int campPos, Vector2Int buildSitePos)
        {
            List<Vector2Int> points = CollectPointsOfInterest(generator, campPos, buildSitePos);
            if (points.Count < 2) return;

            List<(int fromIndex, int toIndex)> edges = NativeBridge.GeneratePathNetwork(points);

            HashSet<Vector2Int> touchedTiles = new HashSet<Vector2Int>();
            foreach (var edge in edges)
            {
                RasterizeLine(points[edge.fromIndex], points[edge.toIndex], generator, touchedTiles);
            }

            foreach (Vector2Int tile in touchedTiles)
            {
                NativeBridge.SetCellWeight(tile.x, tile.y, PathWeight);
            }
        }

        private static List<Vector2Int> CollectPointsOfInterest(PrimsTerrainGenerator generator, Vector2Int campPos, Vector2Int buildSitePos)
        {
            List<Vector2Int> points = new List<Vector2Int> { campPos, buildSitePos };
            points.AddRange(SampleResourceTiles(generator.FindResourceTiles(BiomeType.Wood)));
            points.AddRange(SampleResourceTiles(generator.FindResourceTiles(BiomeType.Food)));
            points.AddRange(SampleResourceTiles(generator.FindResourceTiles(BiomeType.Stone)));
            return points;
        }

        // Spreads a handful of representative points across a resource type's
        // tiles rather than feeding every single tile into the MST (which
        // would produce far more edges than a readable path network needs).
        private static List<Vector2Int> SampleResourceTiles(List<Vector2Int> tiles)
        {
            List<Vector2Int> sampled = new List<Vector2Int>();
            if (tiles.Count == 0) return sampled;

            int step = Mathf.Max(1, tiles.Count / MaxResourceSamplesPerType);
            for (int i = 0; i < tiles.Count && sampled.Count < MaxResourceSamplesPerType; i += step)
            {
                sampled.Add(tiles[i]);
            }
            return sampled;
        }

        // Bresenham line rasterization between two grid points.
        private static void RasterizeLine(Vector2Int from, Vector2Int to, PrimsTerrainGenerator generator, HashSet<Vector2Int> touchedTiles)
        {
            int x0 = from.x, y0 = from.y, x1 = to.x, y1 = to.y;
            int dx = Mathf.Abs(x1 - x0), sx = x0 < x1 ? 1 : -1;
            int dy = -Mathf.Abs(y1 - y0), sy = y0 < y1 ? 1 : -1;
            int err = dx + dy;

            while (true)
            {
                Vector2Int pos = new Vector2Int(x0, y0);
                if (generator.GetBiomeAt(pos.x, pos.y) != BiomeType.Water)
                {
                    generator.ApplyPathTile(pos.x, pos.y);
                    touchedTiles.Add(pos);
                }

                if (x0 == x1 && y0 == y1) break;
                int e2 = 2 * err;
                if (e2 >= dy) { err += dy; x0 += sx; }
                if (e2 <= dx) { err += dx; y0 += sy; }
            }
        }
    }
}
